#!/bin/bash

echo "

choose from 1-3
1,2.fart
3,4.date
5,6.butt"

read -p "enter sselection 1-6 > "
echo "you ve selected $REPLY"

case $REPLY in
	1|2)	echo "fart fart fart"
		exit
		;;

	3|4)	echo $(date)
		exit
		;;

	4|5)	echo "butt butt"
		exit
		;;

	*)	echo "invalid entry" >&2
		exit 1
		;;
esac
