#!/bin/bash


origmass () {
	nf=$1
	thalf=$2
	t=$3
	
	
	n=$(echo "scale=4; $nf / e(l(0.5)*($t/$thalf))" | bc -l)

	return
	}

finlmass () {
	n0=$1
	thalf=$2
	t=$3
	
	echo "$n $thalf $t these are the values"
	echo "$n / 2^($t/$thalf)" | bc -l

	return
	}
decytime() {
	nf=$1
	thalf=$2
	n0=$3
	
	
	t=$(echo "scale=4; $thalf * l($nf / $n0) / l(0.5)" | bc -l)

	return
	}

echo 'halflife is here to help you find answer in relation to half life questions!!'
echo '


choose from 1-2
1.find out original mass
2. find new mass
3. find the time taken'

echo -n 'enter selesction 1-3==> '
read c 


echo "you ve selected $c"

if [[ $c =~ ^[1-3]$ ]]; then
	if [[ $c == 1 ]]; then
		echo "original mass was selected"
		echo -n "please input the halflife of the object ==> "
		read thalf
		echo -n "please input the final mass of the object ==> "
		read nf
		echo -n "please input the how long the object has decayed ==> "
		read t
		origmass $nf $thalf $t
		echo "bob is $n"
		exit
	fi
	if [[ $c == 2 ]]; then
		echo $(date)
		exit
	fi

	if [[ $c == 3 ]]; then
		decytime 2 4 8

		echo "bob is $t"
		exit
	fi
	
	fi
else
	echo 'invalid, cant you read?' 
	
fi

