#!/bin/bash


origmass () {
	nf=$1
	thalf=$2
	t=$3
	
	#why is there a complicated e(l(0.5)*($t/$thalf)) rather then a simple 0.5^($t/$thalf)? because as it turns out ^ only accepet integers
	n=$(echo "scale=4; $nf / e(l(0.5)*($t/$thalf))" | bc -l)

	return
	}

finlmass () {
	n0=$1
	thalf=$2
	t=$3
	
	echo "$n0 $thalf $t these are the values"
	nf=$(echo "scale=4; $n0 * e(l(0.5)*($t/$thalf))" | bc -l)

	return
	}

decytime() {
	nf=$1
	thalf=$2
	n0=$3
	
	
	t=$(echo "scale=4; $thalf * l($nf / $n0) / l(0.5)" | bc -l)

	return
	}

hlflife() {
	nf=$1
	t=$2
	n0=$3

	thalf=$(echo "scale=4; $t *l(0.5) / l($nf / $n0)" | bc -l)

	return
	}
comnmtl() {
	return
	}

wdrmtl() {
	echo "wow the object gained mass, did you do this right?"
	return
	}

echo 'halflife is here to help you find answer in relation to half life questions!!, this is meant for material undergoing decay but should be able to be modified in order to calculate population growth and value depreciation to a certain degree'
echo '


choose from 1-4
1.find out original mass
2. find new mass
3. find the time taken
4. find the half life '

echo -n 'enter selesction 1-4==> '
read c 


echo "you ve selected $c"

if [[ $c =~ ^[1-4]$ ]]; then
	#could the 4 ifs be combined into elifs? does it matter?
	if [[ $c == 1 ]]; then
		echo "original mass was selected"
		#at some point i want to come up with a list of common halflife for materials such as 	u235 and carbon 20 and so on
		echo -n "please input the halflife of the object ==> "
		read thalf
		echo -n "please input the final mass of the object ==> "
		read nf
		echo -n "please input the how long the object has decayed ==> "
		read t
		origmass $nf $thalf $t
		echo "original mass is $n"
		
	fi
	if [[ $c == 2 ]]; then
		echo "fonal mass was selected"
		echo -n "please input the halflife of the object ==> "
		read thalf
		echo -n "please input the original mass of the object ==> "
		read n0
		echo -n "please input the how long the object has decayed ==> "
		read t
		finlmass $n0 $thalf $t
		echo "final mass is $nf"
		
	fi

	if [[ $c == 3 ]]; then
		echo "time taken was selected"
		echo -n "please input the halflife of the object ==> "
		read thalf
		echo -n "please input the original mass of the object ==> "
		read n0
		echo -n "please input the final mass of the object ==> "
		read nf
		if (( $(echo "$n0 > $nf" | bc -l) )); then
			decytime $nf $thalf $n0
			echo "decay time is $t"
		else
			wdrmtl
		fi
		
	fi
	if [[ $c == 4 ]]; then
		echo "time taken was selected"
		echo -n "please input the how long object decayed ==> "
		read t
		echo -n "please input the original mass of the object ==> "
		read n0
		echo -n "please input the final mass of the object ==> "
		read nf
		if (( $(echo "$n0 > $nf" | bc -l) )); then
			hlflife $nf $t $n0
			echo "halflife time is $thalf"
		else
			wdrmtl
		fi
		
	fi

else
	echo 'invalid, cant you read?' 
	
fi

exit


