#!/bin/bash

echo "hello im QA Sample and you have activated me...



for now."

echo -n "enter a number ==>: "
read n

echo "you have printerd $n "

echo -n "enter another number ==>: "
read y

echo "you have printed $y"

